<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TAKO" failures="1" tests="7" name="LoginTest" time="22.931" errors="0" timestamp="2025-05-16T22:50:39 EEST" skipped="0">
  <testcase classname="LoginTest" name="validLogin" time="3.264"/>
  <system-out/>
  <testcase classname="LoginTest" name="lockedUserLogin" time="3.114">
    <failure message="User Should Login expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: User Should Login expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at LoginTest.lockedUserLogin(LoginTest.java:73)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at Main.main(Main.java:19)
]]>
    </failure>
  </testcase> <!-- lockedUserLogin -->
  <system-out/>
  <testcase classname="LoginTest" name="invalidLoginUser" time="2.986"/>
  <system-out/>
  <testcase classname="LoginTest" name="invalidLoginPassword" time="2.550"/>
  <system-out/>
  <testcase classname="LoginTest" name="blankLogin" time="2.999"/>
  <system-out/>
  <testcase classname="LoginTest" name="blankUserNameLogin" time="2.770"/>
  <system-out/>
  <testcase classname="LoginTest" name="blankPasswordLogin" time="5.248"/>
  <system-out/>
</testsuite> <!-- LoginTest -->
